name: Slack Integration
on:
  issue_comment:
    types:
      - created
      - edited
    branches:
      - development
jobs:
  send-pr-message:
    name: Send PR details to Slack
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Preview')
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.comment.body }}"
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "C03SEJ9N1QC"
          payload: |
            {
              "text": ${{ toJSON(github.event.issue.title) }},
              "mrkdwn": true,
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ github.event.issue.title }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(github.event.issue.body) }}
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "${{ github.event.issue.user.avatar_url }}",
                      "alt_text": "${{ github.event.issue.user.login }}"
                    },
                    {
                      "type": "plain_text",
                      "text": "${{ github.event.issue.user.login }}",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(github.event.comment.body) }}
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go to PR",
                        "emoji": true
                      },
                      "value": "click_me_123",
                      "url": "${{ github.event.issue.html_url }}",
                      "action_id": "actionId-0"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
